In [150]:
import pandas as pd

from IPython.display import display, HTML

In [168]:
# there is def a more elegant way to do this but this works

filenames = ["consumer_discretionary/NIKE_Inc_NYSE_NKE_Financials.xls",
"consumer_discretionary/LVMH_Moët_Hennessy_Louis_Vuitton_Société_Européenne_ENXTPA_MC_Financials.xls",
"consumer_discretionary/Starbucks_Corporation_NasdaqGS_SBUX_Financials.xls",
"consumer_discretionary/The_Home_Depot_Inc_NYSE_HD_Financials.xls",

"consumer_non_discretionary/Costco_Wholesale_Corporation_NasdaqGS_COST_Financials.xls",
"consumer_non_discretionary/Johnson_Johnson_NYSE_JNJ_Financials.xls",
"consumer_non_discretionary/Target_Corporation_NYSE_TGT_Financials.xls",
"consumer_non_discretionary/The_Coca_Cola_Company_NYSE_KO_Financials.xls",
"consumer_non_discretionary/The_Procter_Gamble_Company_NYSE_PG_Financials.xls",
"consumer_non_discretionary/Unilever_PLC_LSE_ULVR_Financials.xls",
"consumer_non_discretionary/Walmart_Inc_NYSE_WMT_Financials.xls",

"energy/BP_p_l_c_LSE_BP_Financials.xls",
"energy/Chevron_Corporation_NYSE_CVX_Financials.xls",
"energy/ConocoPhillips_NYSE_COP_Financials.xls",
"energy/Exxon_Mobil_Corporation_NYSE_XOM_Financials.xls",
"energy/Shell_plc_LSE_SHEL_Financials.xls",

"financial_services/Bank_of_America_Corporation_NYSE_BAC_Financials.xls",
"financial_services/Citigroup_Inc_NYSE_C_Financials.xls",
"financial_services/JPMorgan_Chase_Co_NYSE_JPM_Financials_(1).xls",
"financial_services/Mastercard_Incorporated_NYSE_MA_Financials.xls",
"financial_services/Morgan_Stanley_NYSE_MS_Financials.xls",
"financial_services/The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials.xls",
"financial_services/Visa_Inc_NYSE_V_Financials.xls",

"healthcare/Centene_Corporation_NYSE_CNC_Financials.xls",
"healthcare/CVS_Health_Corporation_NYSE_CVS_Financials.xls",
"healthcare/Elevance_Health_Inc_NYSE_ELV_Financials.xls",
"healthcare/McKesson_Corporation_NYSE_MCK_Financials.xls",
"healthcare/The_Cigna_Group_NYSE_CI_Financials.xls",
"healthcare/UnitedHealth_Group_Incorporated_NYSE_UNH_Financials.xls",

"technology/Alphabet_Inc_NasdaqGS_GOOGL_Financials.xls",
"technology/Amazon_com_Inc_NasdaqGS_AMZN_Financials.xls",
"technology/Apple_Inc_NasdaqGS_AAPL_Financials.xls",
"technology/Meta_Platforms_Inc_NasdaqGS_META_Financials.xls",
"technology/Microsoft_Corporation_NasdaqGS_MSFT_Financials.xls",
"technology/Tesla_Inc_NasdaqGS_TSLA_Financials_(1).xls"]

# shell and walmart have weird 'Data Source Change' column names in between some years. removed manually in next cell

# dataframes = list() # stores dataframe for each company

In [254]:
# # go through each file and make a dataframe with the desired rows for each company
# # from the various sheets of the xls files.
# # save dataframe in a list in the format ['filename', dataframe]

# for f in filenames:
#     # picking out the sheets we need from the XLS file
#     # columns once converted from xls to dataframe shift down by two
#     #     for example: Operating income appears on row 33 in the XLS file but corresponds to row 31 in the df
#     # Rows of interest below:
#     # income statement
#         # Row 13: "For the Fiscal Period Ending"
#         # Row 16: Revenue (in millions of usd)
#         # Row 31: Operating income
#         # Row 64: Basic EPS
#         # Row 104: R&D Exp.
#     income_statement = pd.read_excel(f, sheet_name='Income Statement')
#     # ratios
#         # Row 19: Gross margin %
#     ratios = pd.read_excel(f, sheet_name='Ratios')
#     # cash flow
#     #   # Row 42: Cash from investing
#     cash_flow = pd.read_excel(f, sheet_name='Cash Flow')

#     # combine all the rows
#     complete_company_df = income_statement.iloc[[13, 16, 31, 64, 104]]
#     complete_company_df = complete_company_df.append(ratios.iloc[[19]], ignore_index=True)
#     complete_company_df = complete_company_df.append(cash_flow.iloc[[42]], ignore_index=True)

#     # make the first row the new column name, delete old row we got names from
#     complete_company_df.columns = complete_company_df.iloc[0]
#     complete_company_df.drop(index=complete_company_df.index[0], axis=0, inplace=True)
    
#     # drop Data Source Change column if it exists
#     complete_company_df.drop(list(complete_company_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

#     # remove the first X characters from each item in the first row, to get just the year
#     complete_company_df.columns = [col[-4:] for col in complete_company_df.columns]

#     # rename the first column back to what it should be
#     complete_company_df.rename(columns={complete_company_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)

#     dataframes.append([f, complete_company_df])

In [144]:
# # Rearrange all the dataframes so its by metric, not by company

# # Revenue table (first row)
# revenue = pd.DataFrame()

# # Operating income table (second row)
# operating_income = pd.DataFrame()

# # Basic EPS (third row)
# basic_eps = pd.DataFrame()

# # R&D Exp. (fourth row)
# rd_exp = pd.DataFrame()

# # Gross margin % (fifth row)
# gross_margin_percent = pd.DataFrame()

# # Cash from investing (sixth row)
# cash_from_investing = pd.DataFrame()

# all_dataframes = [x[1] for x in dataframes]

# # company = c[1]
# # filename = c[0]
# revenue = pd.concat([all_dataframes[0], all_dataframes[1]], axis=1, sort=False)

WARNING *** file size (827914) not 512 + multiple of sector size (512)
WARNING *** file size (827914) not 512 + multiple of sector size (512)
WARNING *** file size (827914) not 512 + multiple of sector size (512)

In [ ]:
# # create dictionary to hold dataframes for each financial metric
# financial_metrics = {
#     'revenue': pd.DataFrame(columns=['Year']),
#     'operating_income': pd.DataFrame(columns=['Year']),
#     'rd_exp': pd.DataFrame(columns=['Year']),
#     'gross_margin_percentage': pd.DataFrame(columns=['Year']),
#     'cash_from_investing': pd.DataFrame(columns=['Year'])
# }

# # loop through each company dataframe in the masterlist
# for company_data in masterlist:
#     company_name = company_data[0]
#     company_df = company_data[1]
    
#     # loop through each financial metric
#     for metric_name in financial_metrics.keys():
#         metric_df = financial_metrics[metric_name]
        
#         # check if the metric exists in the company dataframe
#         if metric_name in company_df.index:
#             # get the row for the metric and add it to the metric dataframe
#             metric_row = company_df.loc[metric_name]
#             metric_row.name = company_name
#             metric_df = pd.concat([metric_df, metric_row], axis=1)
#             financial_metrics[metric_name] = metric_df

# # merge all the metric dataframes into one dataframe
# metrics_df = pd.concat(financial_metrics.values(), axis=0, keys=financial_metrics.keys())
# metrics_df = metrics_df.swaplevel(axis=0)

# # sort the dataframe by company name and year
# metrics_df = metrics_df.sort_index()

In [190]:
# create lists of dataframes for each metric. 
# we loop through each xml of company data for each company and extract + clean the row we want
# then, we add that dataframe slice to the list of dataframes, and use concat at the end to combine
revenue_df_list = list()

# construct revenue_df
for f in filenames:
    new_df = pd.DataFrame()
    
    income_statement = pd.read_excel(f, sheet_name='Income Statement')
    
    # retrieve the index of the row that contains "Total Revenue". 
    #     Data is not as uniform as described, so it is in different rows in some places
    total_revenue_index = income_statement.index[income_statement.iloc[:,0].str.contains('Total Revenue', na=False)][0]
    
    new_df = income_statement.iloc[[13,total_revenue_index]]
    
    # make the first row the new column name, delete old row we got names from
    new_df.columns = new_df.iloc[0]
    new_df.drop(index=new_df.index[0], axis=0, inplace=True)
    
    # drop Data Source Change column if it exists
    new_df.drop(list(new_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

    # remove the first X characters from each item in the first row, to get just the year
    new_df.columns = [col[-4:] for col in new_df.columns]
    
    # insert the company name as a new row
    new_df.insert(1, "company", f.split('/')[1].split('.')[0])

    # rename the first column back to what it should be
    new_df.rename(columns={new_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)
    
    # remove any duplicated column names
    new_df = new_df.loc[:,~new_df.columns.duplicated()].copy()
    
    revenue_df_list.append(new_df)
    
    # display(HTML(new_df.to_html()))
    
revenue_df = pd.concat(revenue_df_list)

WARNING *** file size (837642) not 512 + multiple of sector size (512)
WARNING *** file size (788490) not 512 + multiple of sector size (512)

/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

WARNING *** file size (723466) not 512 + multiple of sector size (512)
WARNING *** file size (804874) not 512 + multiple of sector size (512)
WARNING *** file size (699914) not 512 + multiple of sector size (512)
WARNING *** file size (811018) not 512 + multiple of sector size (512)
WARNING *** file size (827914) not 512 + multiple of sector size (512)
WARNING *** file size (967178) not 512 + multiple of sector size (512)
WARNING *** file size (866826) not 512 + multiple of sector size (512)
WARNING *** file size (879626) not 512 + multiple of sector size (512)
WARNING *** file size (802314) not 512 + multiple of sector size (512)
WARNING *** file size (857098) not 512 + multiple of sector size (512)
WARNING *** file size (871946) not 512 + multiple of sector size (512)
WARNING *** file size (983562) not 512 + multiple of sector size (512)
WARNING *** file size (899594) not 512 + multiple of sector size (512)
WARNING *** file size (817162) not 512 + multiple of sector size (512)
WARNING *** file size (899594) not 512 + multiple of sector size (512)
WARNING *** file size (901130) not 512 + multiple of sector size (512)
WARNING *** file size (914954) not 512 + multiple of sector size (512)
WARNING *** file size (648714) not 512 + multiple of sector size (512)
WARNING *** file size (755210) not 512 + multiple of sector size (512)
WARNING *** file size (718858) not 512 + multiple of sector size (512)
WARNING *** file size (571914) not 512 + multiple of sector size (512)
WARNING *** file size (229898) not 512 + multiple of sector size (512)
WARNING *** file size (829450) not 512 + multiple of sector size (512)
WARNING *** file size (741898) not 512 + multiple of sector size (512)
WARNING *** file size (833546) not 512 + multiple of sector size (512)
WARNING *** file size (921610) not 512 + multiple of sector size (512)
WARNING *** file size (703498) not 512 + multiple of sector size (512)
WARNING *** file size (521738) not 512 + multiple of sector size (512)
WARNING *** file size (638474) not 512 + multiple of sector size (512)
WARNING *** file size (689162) not 512 + multiple of sector size (512)
WARNING *** file size (350218) not 512 + multiple of sector size (512)
WARNING *** file size (680970) not 512 + multiple of sector size (512)
WARNING *** file size (425994) not 512 + multiple of sector size (512)

In [208]:
# construct operating_income_df
operating_income_df_list = list()
for f in filenames:
    new_df = pd.DataFrame()
    
    income_statement = pd.read_excel(f, sheet_name='Income Statement')
    
    # retrieve the index of the row that contains "Operating Income". 
    #     Data is not as uniform as described, so it is in different rows in some places
    print(f)
    if ('financial_services' in f and 'Mastercard' not in f and 'Morgan_Stanley' not in f and 'Goldman' not in f and 'Visa' not in f):
        # for banks, because they are weird
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Total Other Non-Interest Income', na=False)][0]
    else:
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Operating Income', na=False)][0]
    
    new_df = income_statement.iloc[[13,index]]
    
    # make the first row the new column name, delete old row we got names from
    new_df.columns = new_df.iloc[0]
    new_df.drop(index=new_df.index[0], axis=0, inplace=True)
    
    # drop Data Source Change column if it exists
    new_df.drop(list(new_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

    # remove the first X characters from each item in the first row, to get just the year
    new_df.columns = [col[-4:] for col in new_df.columns]
    
    # insert the company name as a new row
    new_df.insert(1, "company", f.split('/')[1].split('.')[0])

    # rename the first column back to what it should be
    new_df.rename(columns={new_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)
    
    # remove any duplicated column names
    new_df = new_df.loc[:,~new_df.columns.duplicated()].copy()
    
    operating_income_df_list.append(new_df)
    
    # display(HTML(new_df.to_html()))
    
operating_income_df = pd.concat(operating_income_df_list)

WARNING *** file size (837642) not 512 + multiple of sector size (512)
consumer_discretionary/NIKE_Inc_NYSE_NKE_Financials.xls
WARNING *** file size (788490) not 512 + multiple of sector size (512)

/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

consumer_discretionary/LVMH_Moët_Hennessy_Louis_Vuitton_Société_Européenne_ENXTPA_MC_Financials.xls
WARNING *** file size (723466) not 512 + multiple of sector size (512)
consumer_discretionary/Starbucks_Corporation_NasdaqGS_SBUX_Financials.xls
WARNING *** file size (804874) not 512 + multiple of sector size (512)
consumer_discretionary/The_Home_Depot_Inc_NYSE_HD_Financials.xls
WARNING *** file size (699914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Costco_Wholesale_Corporation_NasdaqGS_COST_Financials.xls
WARNING *** file size (811018) not 512 + multiple of sector size (512)
consumer_non_discretionary/Johnson_Johnson_NYSE_JNJ_Financials.xls
WARNING *** file size (827914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Target_Corporation_NYSE_TGT_Financials.xls
WARNING *** file size (967178) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Coca_Cola_Company_NYSE_KO_Financials.xls
WARNING *** file size (866826) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Procter_Gamble_Company_NYSE_PG_Financials.xls
WARNING *** file size (879626) not 512 + multiple of sector size (512)
consumer_non_discretionary/Unilever_PLC_LSE_ULVR_Financials.xls
WARNING *** file size (802314) not 512 + multiple of sector size (512)
consumer_non_discretionary/Walmart_Inc_NYSE_WMT_Financials.xls
WARNING *** file size (857098) not 512 + multiple of sector size (512)
energy/BP_p_l_c_LSE_BP_Financials.xls
WARNING *** file size (871946) not 512 + multiple of sector size (512)
energy/Chevron_Corporation_NYSE_CVX_Financials.xls
WARNING *** file size (983562) not 512 + multiple of sector size (512)
energy/ConocoPhillips_NYSE_COP_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
energy/Exxon_Mobil_Corporation_NYSE_XOM_Financials.xls
WARNING *** file size (817162) not 512 + multiple of sector size (512)
energy/Shell_plc_LSE_SHEL_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
financial_services/Bank_of_America_Corporation_NYSE_BAC_Financials.xls
WARNING *** file size (901130) not 512 + multiple of sector size (512)
financial_services/Citigroup_Inc_NYSE_C_Financials.xls
WARNING *** file size (914954) not 512 + multiple of sector size (512)
financial_services/JPMorgan_Chase_Co_NYSE_JPM_Financials_(1).xls
WARNING *** file size (648714) not 512 + multiple of sector size (512)
financial_services/Mastercard_Incorporated_NYSE_MA_Financials.xls
WARNING *** file size (755210) not 512 + multiple of sector size (512)
financial_services/Morgan_Stanley_NYSE_MS_Financials.xls
WARNING *** file size (718858) not 512 + multiple of sector size (512)
financial_services/The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials.xls
WARNING *** file size (571914) not 512 + multiple of sector size (512)
financial_services/Visa_Inc_NYSE_V_Financials.xls
WARNING *** file size (229898) not 512 + multiple of sector size (512)
healthcare/Centene_Corporation_NYSE_CNC_Financials.xls
WARNING *** file size (829450) not 512 + multiple of sector size (512)
healthcare/CVS_Health_Corporation_NYSE_CVS_Financials.xls
WARNING *** file size (741898) not 512 + multiple of sector size (512)
healthcare/Elevance_Health_Inc_NYSE_ELV_Financials.xls
WARNING *** file size (833546) not 512 + multiple of sector size (512)
healthcare/McKesson_Corporation_NYSE_MCK_Financials.xls
WARNING *** file size (921610) not 512 + multiple of sector size (512)
healthcare/The_Cigna_Group_NYSE_CI_Financials.xls
WARNING *** file size (703498) not 512 + multiple of sector size (512)
healthcare/UnitedHealth_Group_Incorporated_NYSE_UNH_Financials.xls
WARNING *** file size (521738) not 512 + multiple of sector size (512)
technology/Alphabet_Inc_NasdaqGS_GOOGL_Financials.xls
WARNING *** file size (638474) not 512 + multiple of sector size (512)
technology/Amazon_com_Inc_NasdaqGS_AMZN_Financials.xls
WARNING *** file size (689162) not 512 + multiple of sector size (512)
technology/Apple_Inc_NasdaqGS_AAPL_Financials.xls
WARNING *** file size (350218) not 512 + multiple of sector size (512)
technology/Meta_Platforms_Inc_NasdaqGS_META_Financials.xls
WARNING *** file size (680970) not 512 + multiple of sector size (512)
technology/Microsoft_Corporation_NasdaqGS_MSFT_Financials.xls
WARNING *** file size (425994) not 512 + multiple of sector size (512)
technology/Tesla_Inc_NasdaqGS_TSLA_Financials_(1).xls

In [234]:
# construct R&D expenses df
rd_exp_df_list = list()
for f in filenames:
    new_df = pd.DataFrame()
    
    income_statement = pd.read_excel(f, sheet_name='Income Statement')
    
    # retrieve the index of the row that contains "Operating Income". 
    #     Data is not as uniform as described, so it is in different rows in some places
    print(f)
    if ('Bank_of_America' in f or 'Citigroup' in f or 'JPM' in f):
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Total Other Non-Interest Expense', na=False)][0]
    elif ('Centene' in f):
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Other Operating Exp.', na=False)][0]
    elif ('Elevance' in f):
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Selling and Marketing Exp.', na=False)][0]
    elif ('UnitedHealth' in f):
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Selling General & Admin Exp., Total', na=False)][0]
    elif ('Morgan_Stanley' or 'Goldman' in f):
        index = income_statement.index[income_statement.iloc[:,0].str.contains('Other Non-Operating Inc.', na=False)][0]
    elif ('Home_Depot' or 'Costco' in f):
        index = income_statement.index[income_statement.iloc[:,0].str.contains('R & D Exp.', na=False)][0]
    else:
        index = income_statement.index[income_statement.iloc[:,0].str.contains('R&D Exp.', na=False)][0]   
    
    
    new_df = income_statement.iloc[[13,index]]
    
    # make the first row the new column name, delete old row we got names from
    new_df.columns = new_df.iloc[0]
    new_df.drop(index=new_df.index[0], axis=0, inplace=True)
    
    # drop Data Source Change column if it exists
    new_df.drop(list(new_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

    # remove the first X characters from each item in the first row, to get just the year
    new_df.columns = [col[-4:] for col in new_df.columns]
    
    # insert the company name as a new row
    new_df.insert(1, "company", f.split('/')[1].split('.')[0])

    # rename the first column back to what it should be
    new_df.rename(columns={new_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)
    
    # remove any duplicated column names
    new_df = new_df.loc[:,~new_df.columns.duplicated()].copy()
    
    rd_exp_df_list.append(new_df)
    
    # display(HTML(new_df.to_html()))
    
rd_exp_df = pd.concat(rd_exp_df_list)

WARNING *** file size (837642) not 512 + multiple of sector size (512)
consumer_discretionary/NIKE_Inc_NYSE_NKE_Financials.xls
WARNING *** file size (788490) not 512 + multiple of sector size (512)
consumer_discretionary/LVMH_Moët_Hennessy_Louis_Vuitton_Société_Européenne_ENXTPA_MC_Financials.xls
WARNING *** file size (723466) not 512 + multiple of sector size (512)
consumer_discretionary/Starbucks_Corporation_NasdaqGS_SBUX_Financials.xls
WARNING *** file size (804874) not 512 + multiple of sector size (512)
consumer_discretionary/The_Home_Depot_Inc_NYSE_HD_Financials.xls
WARNING *** file size (699914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Costco_Wholesale_Corporation_NasdaqGS_COST_Financials.xls
WARNING *** file size (811018) not 512 + multiple of sector size (512)
consumer_non_discretionary/Johnson_Johnson_NYSE_JNJ_Financials.xls
WARNING *** file size (827914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Target_Corporation_NYSE_TGT_Financials.xls
WARNING *** file size (967178) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Coca_Cola_Company_NYSE_KO_Financials.xls
WARNING *** file size (866826) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Procter_Gamble_Company_NYSE_PG_Financials.xls
WARNING *** file size (879626) not 512 + multiple of sector size (512)
consumer_non_discretionary/Unilever_PLC_LSE_ULVR_Financials.xls
WARNING *** file size (802314) not 512 + multiple of sector size (512)
consumer_non_discretionary/Walmart_Inc_NYSE_WMT_Financials.xls
WARNING *** file size (857098) not 512 + multiple of sector size (512)
energy/BP_p_l_c_LSE_BP_Financials.xls
WARNING *** file size (871946) not 512 + multiple of sector size (512)
energy/Chevron_Corporation_NYSE_CVX_Financials.xls
WARNING *** file size (983562) not 512 + multiple of sector size (512)
energy/ConocoPhillips_NYSE_COP_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
energy/Exxon_Mobil_Corporation_NYSE_XOM_Financials.xls
WARNING *** file size (817162) not 512 + multiple of sector size (512)
energy/Shell_plc_LSE_SHEL_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
financial_services/Bank_of_America_Corporation_NYSE_BAC_Financials.xls
WARNING *** file size (901130) not 512 + multiple of sector size (512)
financial_services/Citigroup_Inc_NYSE_C_Financials.xls
WARNING *** file size (914954) not 512 + multiple of sector size (512)
financial_services/JPMorgan_Chase_Co_NYSE_JPM_Financials_(1).xls
WARNING *** file size (648714) not 512 + multiple of sector size (512)
financial_services/Mastercard_Incorporated_NYSE_MA_Financials.xls
WARNING *** file size (755210) not 512 + multiple of sector size (512)
financial_services/Morgan_Stanley_NYSE_MS_Financials.xls
WARNING *** file size (718858) not 512 + multiple of sector size (512)
financial_services/The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials.xls
WARNING *** file size (571914) not 512 + multiple of sector size (512)
financial_services/Visa_Inc_NYSE_V_Financials.xls
WARNING *** file size (229898) not 512 + multiple of sector size (512)
healthcare/Centene_Corporation_NYSE_CNC_Financials.xls
WARNING *** file size (829450) not 512 + multiple of sector size (512)
healthcare/CVS_Health_Corporation_NYSE_CVS_Financials.xls
WARNING *** file size (741898) not 512 + multiple of sector size (512)
healthcare/Elevance_Health_Inc_NYSE_ELV_Financials.xls
WARNING *** file size (833546) not 512 + multiple of sector size (512)
healthcare/McKesson_Corporation_NYSE_MCK_Financials.xls
WARNING *** file size (921610) not 512 + multiple of sector size (512)
healthcare/The_Cigna_Group_NYSE_CI_Financials.xls
WARNING *** file size (703498) not 512 + multiple of sector size (512)
healthcare/UnitedHealth_Group_Incorporated_NYSE_UNH_Financials.xls
WARNING *** file size (521738) not 512 + multiple of sector size (512)
technology/Alphabet_Inc_NasdaqGS_GOOGL_Financials.xls
WARNING *** file size (638474) not 512 + multiple of sector size (512)
technology/Amazon_com_Inc_NasdaqGS_AMZN_Financials.xls
WARNING *** file size (689162) not 512 + multiple of sector size (512)
technology/Apple_Inc_NasdaqGS_AAPL_Financials.xls
WARNING *** file size (350218) not 512 + multiple of sector size (512)
technology/Meta_Platforms_Inc_NasdaqGS_META_Financials.xls
WARNING *** file size (680970) not 512 + multiple of sector size (512)
technology/Microsoft_Corporation_NasdaqGS_MSFT_Financials.xls
WARNING *** file size (425994) not 512 + multiple of sector size (512)
technology/Tesla_Inc_NasdaqGS_TSLA_Financials_(1).xls

In [235]:
rd_exp_df

,For the Fiscal Period Ending,company,1984,1985,1986,1987,1988,1989,1990,1991,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,ange
38,Other Non-Operating Inc. (Exp.),NIKE_Inc_NYSE_NKE_Financials,0.175,0.013,-11.2,6.201,20.722,3.449,7.264,0.043,...,131,563,255,44,39,236,208,58,106,NaN
39,Other Non-Operating Inc. (Exp.),LVMH_Moët_Hennessy_Louis_Vuitton_Société_Eu...,NaN,NaN,NaN,NaN,NaN,-5.2,9.019608,0.385253,...,-34.8,-50.7,-20.4,-27.5,-25.8,-41.6,-54.6,-47,NaN,NaN
38,Other Non-Operating Inc. (Exp.),Starbucks_Corporation_NasdaqGS_SBUX_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,-26.9,58.4,92.1,157.2,-7.8,-10.5,2.6,-2.5,9.2,NaN
37,Other Non-Operating Inc. (Exp.),The_Home_Depot_Inc_NYSE_HD_Financials,NaN,-,-,-,-,-,-,-,...,-,-,-,-,-16,-,-,-,-,NaN
39,Other Non-Operating Inc. (Exp.),Costco_Wholesale_Corporation_NasdaqGS_COST_Fin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,7,11,17,23,25,32,46,38,38,NaN
37,Other Non-Operating Inc. (Exp.),Johnson_Johnson_NYSE_JNJ_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-85,...,NaN,416,197,1027,289,NaN,469,991,1832,NaN
39,Other Non-Operating Inc. (Exp.),Target_Corporation_NYSE_TGT_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,2,3,-4,18,2,NaN
39,Other Non-Operating Inc. (Exp.),The_Coca_Cola_Company_NYSE_KO_Financials,NaN,NaN,42.837,0.034,-33.2,4.847,13.727,41.368,...,25,113,53,386,-326,-38,-15,-847,NaN,NaN
36,Other Non-Operating Inc. (Exp.),The_Procter_Gamble_Company_NYSE_PG_Financials,NaN,NaN,NaN,NaN,NaN,-,-,-,...,131,24,19,23,490,772,71,-8,NaN,NaN
38,Other Non-Operating Inc. (Exp.),Unilever_PLC_LSE_ULVR_Financials,NaN,NaN,NaN,NaN,NaN,NaN,47.963051,62.5,...,-,-,-31.2,-17.2,-6.7,-25.7,-10.2,-21.4,NaN,NaN
36,Other Non-Operating Inc. (Exp.),Walmart_Inc_NYSE_WMT_Financials,NaN,NaN,-,-,-,-,-,-,...,-,-,-,-,-2,87,22,-127,-455,NaN
40,Other Non-Operating Inc. (Exp.),BP_p_l_c_LSE_BP_Financials,NaN,NaN,NaN,NaN,NaN,422.999,385.7,309.756,...,-,-,-,253,291,105,282,-15,NaN,NaN
40,Other Non-Operating Inc. (Exp.),Chevron_Corporation_NYSE_CVX_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,334,...,470,488,441,325,1318,-74,227,1390,NaN,NaN
40,Other Non-Operating Inc. (Exp.),ConocoPhillips_NYSE_COP_Financials,NaN,NaN,NaN,NaN,-,-,-,-,...,-,111,80,93,557,241,120,-20,NaN,NaN
40,Other Non-Operating Inc. (Exp.),Exxon_Mobil_Corporation_NYSE_XOM_Financials,NaN,NaN,NaN,NaN,NaN,NaN,-,-,...,1552,998,-,1728,1214,-,-,-,NaN,NaN
40,Other Non-Operating Inc. (Exp.),Shell_plc_LSE_SHEL_Financials,NaN,NaN,NaN,NaN,NaN,2336.1815,1903.429499,1830.545999,...,43,-,227,104,179,273,341,477,NaN,NaN
47,Total Other Non-Interest Expense,Bank_of_America_Corporation_NYSE_BAC_Financials,NaN,NaN,NaN,NaN,NaN,3239,3538,3974,...,8145,8136,9928,7967,5405,6730,6970,7674,NaN,NaN
42,Total Other Non-Interest Expense,Citigroup_Inc_NYSE_C_Financials,NaN,NaN,NaN,NaN,NaN,NaN,2917,3638,...,11645,9820,9052,9839,9813,11590,10755,12635,NaN,NaN
46,Total Other Non-Interest Expense,JPMorgan_Chase_Co_NYSE_JPM_Financials_(1),NaN,NaN,NaN,NaN,NaN,NaN,276,343,...,6624,6073,6291,5485,4847,4826,5036,6099,NaN,NaN
37,Other Non-Operating Inc. (Exp.),Mastercard_Incorporated_NYSE_MA_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-84,-63,-2,-22,24,-3,-10,19,NaN,NaN
41,Other Non-Operating Inc. (Exp.),Morgan_Stanley_NYSE_MS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2017,-1834,-2018,-2230,-2126,-2928,-3487,-3131,NaN,FYC
40,Other Non-Operating Inc. (Exp.),The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,-,-,NaN,FYC
38,Other Non-Operating Inc. (Exp.),Visa_Inc_NYSE_V_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-115,255,8,-6,-,-8,-19,34,NaN,NaN
29,Other Operating Exp.,Centene_Corporation_NYSE_CNC_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1968,1957,2659,2320,5182,7294,NaN,NaN
36,Other Non-Operating Inc. (Exp.),CVS_Health_Corporation_NYSE_CVS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,-,-,...,-,-32,-208,-2,-7,-12,-4,-4,NaN,NaN
100,Selling and Marketing Exp.,Elevance_Health_Inc_NYSE_ELV_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1441.1,1391.5,1395.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Other Non-Operating Inc. (Exp.),McKesson_Corporation_NYSE_MCK_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31,29,41,107,154,64,30,66,NaN,NaN
38,Other Non-Operating Inc. (Exp.),The_Cigna_Group_NYSE_CI_Financials,NaN,NaN,NaN,NaN,-,-,-,-,...,-,-,-,41,78,-52,181,137,NaN,NaN
28,"Selling General & Admin Exp., Total",UnitedHealth_Group_Incorporated_NYSE_UNH_Finan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24312,28401,29557,34074,35193,41704,42579,47782,NaN,NaN
38,Other Non-Operating Inc. (Exp.),Alphabet_Inc_NasdaqGS_GOOGL_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,152,88,159,378,-224,-344,-1589,1179,NaN,NaN
39,Other Non-Operating Inc. (Exp.),Amazon_com_Inc_NasdaqGS_AMZN_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,10,-3,17,-23,-33,-19,-540,NaN,NaN
37,Other Non-Operating Inc. (Exp.),Apple_Inc_NasdaqGS_AAPL_Financials,NaN,NaN,NaN,NaN,-,-,-,-,...,-356,-997,-870,-117,1237,-773,60,-228,NaN,NaN
37,Other Non-Operating Inc. (Exp.),Meta_Platforms_Inc_NasdaqGS_META_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,1,5,9,27,-34,210,-320,NaN,NaN
38,Other Non-Operating Inc. (Exp.),Microsoft_Corporation_NasdaqGS_MSFT_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-16.5,...,142,-239,-116,-54,77,127,20,-407,NaN,NaN
37,Other Non-Operating Inc. (Exp.),Tesla_Inc_NasdaqGS_TSLA_Financials_(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.948,3.645,-15.3,10.478,37,28,25,46,NaN,NaN

In [245]:
gross_margin_percentage_df_list = list()
for f in filenames:
    new_df = pd.DataFrame()
    
    ratio_statement = pd.read_excel(f, sheet_name='Ratios')
    
    # retrieve the index of the row that contains "Gross Margin %. 
    #     Data is not as uniform as described, so it is in different rows in some places
    print(f)
    if ('Bank_of_America' or 'Citi' in f):
        index = ratio_statement.index[ratio_statement.iloc[:,0].str.contains('SG&A Margin %', na=False)][0]
    else: 
        index = ratio_statement.index[ratio_statement.iloc[:,0].str.contains('Gross Margin %', na=False)][0]
    
    new_df = ratio_statement.iloc[[11,index]]
    
    # make the first row the new column name, delete old row we got names from
    new_df.columns = new_df.iloc[0]
    new_df.drop(index=new_df.index[0], axis=0, inplace=True)
    
    # drop Data Source Change column if it exists
    new_df.drop(list(new_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

    # remove the first X characters from each item in the first row, to get just the year
    new_df.columns = [col[-4:] for col in new_df.columns]
    
    # insert the company name as a new row
    new_df.insert(1, "company", f.split('/')[1].split('.')[0])

    # rename the first column back to what it should be
    new_df.rename(columns={new_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)
    
    # remove any duplicated column names
    new_df = new_df.loc[:,~new_df.columns.duplicated()].copy()
    
    gross_margin_percentage_df_list.append(new_df)
    
    # display(HTML(new_df.to_html()))
    
gross_margin_percentage_df = pd.concat(gross_margin_percentage_df_list)

WARNING *** file size (837642) not 512 + multiple of sector size (512)
consumer_discretionary/NIKE_Inc_NYSE_NKE_Financials.xls
WARNING *** file size (788490) not 512 + multiple of sector size (512)
consumer_discretionary/LVMH_Moët_Hennessy_Louis_Vuitton_Société_Européenne_ENXTPA_MC_Financials.xls
WARNING *** file size (723466) not 512 + multiple of sector size (512)
consumer_discretionary/Starbucks_Corporation_NasdaqGS_SBUX_Financials.xls
WARNING *** file size (804874) not 512 + multiple of sector size (512)
consumer_discretionary/The_Home_Depot_Inc_NYSE_HD_Financials.xls
WARNING *** file size (699914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Costco_Wholesale_Corporation_NasdaqGS_COST_Financials.xls
WARNING *** file size (811018) not 512 + multiple of sector size (512)
consumer_non_discretionary/Johnson_Johnson_NYSE_JNJ_Financials.xls
WARNING *** file size (827914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Target_Corporation_NYSE_TGT_Financials.xls
WARNING *** file size (967178) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Coca_Cola_Company_NYSE_KO_Financials.xls
WARNING *** file size (866826) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Procter_Gamble_Company_NYSE_PG_Financials.xls
WARNING *** file size (879626) not 512 + multiple of sector size (512)
consumer_non_discretionary/Unilever_PLC_LSE_ULVR_Financials.xls
WARNING *** file size (802314) not 512 + multiple of sector size (512)
consumer_non_discretionary/Walmart_Inc_NYSE_WMT_Financials.xls
WARNING *** file size (857098) not 512 + multiple of sector size (512)
energy/BP_p_l_c_LSE_BP_Financials.xls
WARNING *** file size (871946) not 512 + multiple of sector size (512)
energy/Chevron_Corporation_NYSE_CVX_Financials.xls
WARNING *** file size (983562) not 512 + multiple of sector size (512)
energy/ConocoPhillips_NYSE_COP_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
energy/Exxon_Mobil_Corporation_NYSE_XOM_Financials.xls
WARNING *** file size (817162) not 512 + multiple of sector size (512)
energy/Shell_plc_LSE_SHEL_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
financial_services/Bank_of_America_Corporation_NYSE_BAC_Financials.xls
WARNING *** file size (901130) not 512 + multiple of sector size (512)
financial_services/Citigroup_Inc_NYSE_C_Financials.xls
WARNING *** file size (914954) not 512 + multiple of sector size (512)
financial_services/JPMorgan_Chase_Co_NYSE_JPM_Financials_(1).xls
WARNING *** file size (648714) not 512 + multiple of sector size (512)
financial_services/Mastercard_Incorporated_NYSE_MA_Financials.xls
WARNING *** file size (755210) not 512 + multiple of sector size (512)
financial_services/Morgan_Stanley_NYSE_MS_Financials.xls
WARNING *** file size (718858) not 512 + multiple of sector size (512)
financial_services/The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials.xls
WARNING *** file size (571914) not 512 + multiple of sector size (512)
financial_services/Visa_Inc_NYSE_V_Financials.xls
WARNING *** file size (229898) not 512 + multiple of sector size (512)
healthcare/Centene_Corporation_NYSE_CNC_Financials.xls
WARNING *** file size (829450) not 512 + multiple of sector size (512)
healthcare/CVS_Health_Corporation_NYSE_CVS_Financials.xls
WARNING *** file size (741898) not 512 + multiple of sector size (512)
healthcare/Elevance_Health_Inc_NYSE_ELV_Financials.xls
WARNING *** file size (833546) not 512 + multiple of sector size (512)
healthcare/McKesson_Corporation_NYSE_MCK_Financials.xls
WARNING *** file size (921610) not 512 + multiple of sector size (512)
healthcare/The_Cigna_Group_NYSE_CI_Financials.xls
WARNING *** file size (703498) not 512 + multiple of sector size (512)
healthcare/UnitedHealth_Group_Incorporated_NYSE_UNH_Financials.xls
WARNING *** file size (521738) not 512 + multiple of sector size (512)
technology/Alphabet_Inc_NasdaqGS_GOOGL_Financials.xls
WARNING *** file size (638474) not 512 + multiple of sector size (512)
technology/Amazon_com_Inc_NasdaqGS_AMZN_Financials.xls
WARNING *** file size (689162) not 512 + multiple of sector size (512)
technology/Apple_Inc_NasdaqGS_AAPL_Financials.xls
WARNING *** file size (350218) not 512 + multiple of sector size (512)
technology/Meta_Platforms_Inc_NasdaqGS_META_Financials.xls
WARNING *** file size (680970) not 512 + multiple of sector size (512)
technology/Microsoft_Corporation_NasdaqGS_MSFT_Financials.xls
WARNING *** file size (425994) not 512 + multiple of sector size (512)
technology/Tesla_Inc_NasdaqGS_TSLA_Financials_(1).xls

In [252]:
cash_from_investing_df_list = list()
for f in filenames:
    new_df = pd.DataFrame()
    
    cash_flow_statement = pd.read_excel(f, sheet_name='Cash Flow')
    
    # retrieve the index of the row that contains "Cash from Investing". 
    #     Data is not as uniform as described, so it is in different rows in some places
    print(f)
    index = cash_flow_statement.index[cash_flow_statement.iloc[:,0].str.contains('Cash from Investing', na=False)][0]
    new_df = cash_flow_statement.iloc[[13,index]]
    
    # make the first row the new column name, delete old row we got names from
    new_df.columns = new_df.iloc[0]
    new_df.drop(index=new_df.index[0], axis=0, inplace=True)
    
    # drop Data Source Change column if it exists
    new_df.drop(list(new_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

    # remove the first X characters from each item in the first row, to get just the year
    new_df.columns = [col[-4:] for col in new_df.columns]
    
    # insert the company name as a new row
    new_df.insert(1, "company", f.split('/')[1].split('.')[0])

    # rename the first column back to what it should be
    new_df.rename(columns={new_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)
    
    # remove any duplicated column names
    new_df = new_df.loc[:,~new_df.columns.duplicated()].copy()
    
    cash_from_investing_df_list.append(new_df)
    
    # display(HTML(new_df.to_html()))
    
cash_from_investing_df = pd.concat(cash_from_investing_df_list)

WARNING *** file size (837642) not 512 + multiple of sector size (512)
consumer_discretionary/NIKE_Inc_NYSE_NKE_Financials.xls
WARNING *** file size (788490) not 512 + multiple of sector size (512)
consumer_discretionary/LVMH_Moët_Hennessy_Louis_Vuitton_Société_Européenne_ENXTPA_MC_Financials.xls
WARNING *** file size (723466) not 512 + multiple of sector size (512)

/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

consumer_discretionary/Starbucks_Corporation_NasdaqGS_SBUX_Financials.xls
WARNING *** file size (804874) not 512 + multiple of sector size (512)
consumer_discretionary/The_Home_Depot_Inc_NYSE_HD_Financials.xls
WARNING *** file size (699914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Costco_Wholesale_Corporation_NasdaqGS_COST_Financials.xls
WARNING *** file size (811018) not 512 + multiple of sector size (512)
consumer_non_discretionary/Johnson_Johnson_NYSE_JNJ_Financials.xls
WARNING *** file size (827914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Target_Corporation_NYSE_TGT_Financials.xls
WARNING *** file size (967178) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Coca_Cola_Company_NYSE_KO_Financials.xls
WARNING *** file size (866826) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Procter_Gamble_Company_NYSE_PG_Financials.xls
WARNING *** file size (879626) not 512 + multiple of sector size (512)
consumer_non_discretionary/Unilever_PLC_LSE_ULVR_Financials.xls
WARNING *** file size (802314) not 512 + multiple of sector size (512)
consumer_non_discretionary/Walmart_Inc_NYSE_WMT_Financials.xls
WARNING *** file size (857098) not 512 + multiple of sector size (512)
energy/BP_p_l_c_LSE_BP_Financials.xls
WARNING *** file size (871946) not 512 + multiple of sector size (512)
energy/Chevron_Corporation_NYSE_CVX_Financials.xls
WARNING *** file size (983562) not 512 + multiple of sector size (512)
energy/ConocoPhillips_NYSE_COP_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
energy/Exxon_Mobil_Corporation_NYSE_XOM_Financials.xls
WARNING *** file size (817162) not 512 + multiple of sector size (512)
energy/Shell_plc_LSE_SHEL_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
financial_services/Bank_of_America_Corporation_NYSE_BAC_Financials.xls
WARNING *** file size (901130) not 512 + multiple of sector size (512)
financial_services/Citigroup_Inc_NYSE_C_Financials.xls
WARNING *** file size (914954) not 512 + multiple of sector size (512)
financial_services/JPMorgan_Chase_Co_NYSE_JPM_Financials_(1).xls
WARNING *** file size (648714) not 512 + multiple of sector size (512)
financial_services/Mastercard_Incorporated_NYSE_MA_Financials.xls
WARNING *** file size (755210) not 512 + multiple of sector size (512)
financial_services/Morgan_Stanley_NYSE_MS_Financials.xls
WARNING *** file size (718858) not 512 + multiple of sector size (512)
financial_services/The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials.xls
WARNING *** file size (571914) not 512 + multiple of sector size (512)
financial_services/Visa_Inc_NYSE_V_Financials.xls
WARNING *** file size (229898) not 512 + multiple of sector size (512)
healthcare/Centene_Corporation_NYSE_CNC_Financials.xls
WARNING *** file size (829450) not 512 + multiple of sector size (512)
healthcare/CVS_Health_Corporation_NYSE_CVS_Financials.xls
WARNING *** file size (741898) not 512 + multiple of sector size (512)
healthcare/Elevance_Health_Inc_NYSE_ELV_Financials.xls
WARNING *** file size (833546) not 512 + multiple of sector size (512)
healthcare/McKesson_Corporation_NYSE_MCK_Financials.xls
WARNING *** file size (921610) not 512 + multiple of sector size (512)
healthcare/The_Cigna_Group_NYSE_CI_Financials.xls
WARNING *** file size (703498) not 512 + multiple of sector size (512)
healthcare/UnitedHealth_Group_Incorporated_NYSE_UNH_Financials.xls
WARNING *** file size (521738) not 512 + multiple of sector size (512)
technology/Alphabet_Inc_NasdaqGS_GOOGL_Financials.xls
WARNING *** file size (638474) not 512 + multiple of sector size (512)
technology/Amazon_com_Inc_NasdaqGS_AMZN_Financials.xls
WARNING *** file size (689162) not 512 + multiple of sector size (512)
technology/Apple_Inc_NasdaqGS_AAPL_Financials.xls
WARNING *** file size (350218) not 512 + multiple of sector size (512)
technology/Meta_Platforms_Inc_NasdaqGS_META_Financials.xls
WARNING *** file size (680970) not 512 + multiple of sector size (512)
technology/Microsoft_Corporation_NasdaqGS_MSFT_Financials.xls
WARNING *** file size (425994) not 512 + multiple of sector size (512)
technology/Tesla_Inc_NasdaqGS_TSLA_Financials_(1).xls

In [253]:
cash_from_investing_df

,For the Fiscal Period Ending,company,1984,1985,1986,1987,1988,1989,1990,1991,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,ange
43,Cash from Investing,NIKE_Inc_NYSE_NKE_Financials,-20.5,-23.6,-0.2,-11.1,-113.2,-40.5,-89.4,-211.2,...,-175,-1034,-1008,276,-264,-1028,-3800,-1524,-,NaN
42,Cash from Investing,LVMH_Moët_Hennessy_Louis_Vuitton_Société_Eu...,NaN,NaN,NaN,NaN,NaN,-,-,-,...,-2678.3,-2477.6,-10335,-3937.5,-6586.2,-3595.1,-18172.4,-6326.8,NaN,NaN
46,Cash from Investing,Starbucks_Corporation_NasdaqGS_SBUX_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7,...,-1520.3,-2222.9,-850,-2361.5,-1010.8,-1711.5,-319.5,-2146.3,-2024.6,NaN
42,Cash from Investing,The_Home_Depot_Inc_NYSE_HD_Financials,NaN,-78.5,-,-15.9,-87.4,-103.4,-255.4,-368.8,...,-1271,-2982,-1583,-2228,-2416,-2653,-10170,-2969,-3140,NaN
45,Cash from Investing,Costco_Wholesale_Corporation_NasdaqGS_COST_Fin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-688.4,...,-2480,-2345,-2366,-2947,-2865,-3891,-3535,-3915,-4387,NaN
42,Cash from Investing,Johnson_Johnson_NYSE_JNJ_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1028,...,NaN,-7735,-4761,-3167,-6194,NaN,-20825,-8683,-12371,NaN
42,Cash from Investing,Target_Corporation_NYSE_TGT_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1926,508,-1473,-3075,-3416,-2944,-2591,-3154,-5504,NaN
45,Cash from Investing,The_Coca_Cola_Company_NYSE_KO_Financials,NaN,NaN,-451,-403.8,349.902,553.878,-439.7,-1124.7,...,-6186,-999,-2450,5927,-3976,-1477,-2765,-763,NaN,NaN
39,Cash from Investing,The_Procter_Gamble_Company_NYSE_PG_Financials,NaN,NaN,NaN,NaN,NaN,-1437,-1521,-2183,...,-2891,-5575,-5689,-3511,-3490,3045,-2834,-4424,NaN,NaN
42,Cash from Investing,Unilever_PLC_LSE_ULVR_Financials,NaN,NaN,NaN,NaN,NaN,NaN,-,-,...,-3843.6,-3365.4,-7059.3,5317.151362,-2510.4,-1811.6,-3691.6,2621.566741,NaN,NaN
40,Cash from Investing,Walmart_Inc_NYSE_WMT_Financials,NaN,NaN,-525.8,-500.1,-676.2,-541.1,-893.8,-1526.1,...,-11125,-10675,-13987,-9060,-24036,-9128,-10071,-6015,-17722,NaN
43,Cash from Investing,BP_p_l_c_LSE_BP_Financials,NaN,NaN,NaN,NaN,NaN,-,-,-,...,-17300,-14753,-14077,-21571,-16974,-7858,-5694,-13713,NaN,NaN
42,Cash from Investing,Chevron_Corporation_NYSE_CVX_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2907,...,-23808,-16852,-8201,-12290,-11458,-6965,-5865,-12108,NaN,NaN
42,Cash from Investing,ConocoPhillips_NYSE_COP_Financials,NaN,NaN,NaN,NaN,-710,-938,-708,-1333,...,-8655,-3859,7762,-3843,-6618,-4121,-8544,-8741,NaN,NaN
41,Cash from Investing,Exxon_Mobil_Corporation_NYSE_XOM_Financials,NaN,NaN,NaN,NaN,NaN,NaN,-5169,-6220,...,-23824,-12403,-15730,-16446,-23084,-18459,-10235,-14742,NaN,NaN
45,Cash from Investing,Shell_plc_LSE_SHEL_Financials,NaN,NaN,NaN,NaN,NaN,-,-,-,...,-22407,-30963,-8029,-13659,-15779,-13278,-4761,-22448,NaN,NaN
45,Cash from Investing,Bank_of_America_Corporation_NYSE_BAC_Financials,NaN,NaN,NaN,NaN,NaN,-14271,-3028,4525,...,-54954,-63143,-52007,-71468,-80630,-177665,-313291,-2529,NaN,NaN
46,Cash from Investing,Citigroup_Inc_NYSE_C_Financials,NaN,NaN,NaN,NaN,NaN,NaN,-2016,-819,...,14883,-79588,-58228,-73118,-23374,-95312,-124905,-79455,NaN,NaN
43,Cash from Investing,JPMorgan_Chase_Co_NYSE_JPM_Financials_(1),NaN,NaN,NaN,NaN,NaN,NaN,1311,-950,...,106980,-114949,-10283,-197993,-54013,-261912,-129344,-137819,NaN,NaN
42,Cash from Investing,Mastercard_Incorporated_NYSE_MA_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-715,-1167,-1779,-506,-1640,-1879,-5272,-1470,NaN,NaN
45,Cash from Investing,Morgan_Stanley_NYSE_MS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-19995,-19508,-12391,-22881,-33561,-37898,-49897,-11632,NaN,FYC
41,Cash from Investing,The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-18574,9270,-29116,-22677,-24236,-34356,-30465,-75960,NaN,FYC
46,Cash from Investing,Visa_Inc_NYSE_V_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1435,-10916,735,-3084,-591,1427,-152,-4288,NaN,NaN
41,Cash from Investing,Centene_Corporation_NYSE_CNC_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-1265,-4585,-1532,-6955,-3299,-2921,NaN,NaN
44,Cash from Investing,CVS_Health_Corporation_NYSE_CVS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,-628,-237.2,...,-13420,-2470,-2932,-43285,-3339,-5534,-5261,-5047,NaN,NaN
46,Cash from Investing,Elevance_Health_Inc_NYSE_ELV_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1151.5,-513.9,-5082.4,-1259,-2792,-7324,-9638,-4560,NaN,NaN
47,Cash from Investing,McKesson_Corporation_NYSE_MCK_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-677,-1557,-3796,-1522,-1381,-579,-415,-89,NaN,NaN
49,Cash from Investing,The_Cigna_Group_NYSE_CI_Financials,NaN,NaN,NaN,NaN,-1994,-1893,-2243,-2755,...,-1599,-2574,-1703,-26378,-734,2976,-3611,3098,NaN,NaN
42,Cash from Investing,UnitedHealth_Group_Incorporated_NYSE_UNH_Finan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-18395,-9355,-8599,-12385,-12699,-12532,-10372,-28476,NaN,NaN
45,Cash from Investing,Alphabet_Inc_NasdaqGS_GOOGL_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-23711,-31165,-31401,-28504,-29491,-32773,-35523,-20298,NaN,NaN
42,Cash from Investing,Amazon_com_Inc_NasdaqGS_AMZN_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-6450,-9876,-27819,-12369,-24281,-59611,-58154,-37601,NaN,NaN
45,Cash from Investing,Apple_Inc_NasdaqGS_AAPL_Financials,NaN,NaN,NaN,NaN,-184,-403.1,-573.5,58.324,...,-56274,-45977,-46446,16066,45896,-4289,-14545,-22354,NaN,NaN
41,Cash from Investing,Meta_Platforms_Inc_NasdaqGS_META_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-9434,-11739,-20038,-11603,-19864,-30059,-7570,-28970,NaN,NaN
42,Cash from Investing,Microsoft_Corporation_NasdaqGS_MSFT_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-381,...,-23001,-23950,-46781,-6061,-15773,-12223,-27577,-30311,NaN,NaN
42,Cash from Investing,Tesla_Inc_NasdaqGS_TSLA_Financials_(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1673.6,-1416.4,-4419,-2337.4,-1436,-3132,-7868,-11973,NaN,NaN

In [255]:
# construct basic eps df
basic_eps_df_list = list()
for f in filenames:
    new_df = pd.DataFrame()
    
    income_statement = pd.read_excel(f, sheet_name='Income Statement')
    
    # retrieve the index of the row that contains "Basic EPS". 
    #     Data is not as uniform as described, so it is in different rows in some places
    print(f)
    index = income_statement.index[income_statement.iloc[:,0].str.contains('Basic EPS', na=False)][0]   
    
    
    new_df = income_statement.iloc[[13,index]]
    
    # make the first row the new column name, delete old row we got names from
    new_df.columns = new_df.iloc[0]
    new_df.drop(index=new_df.index[0], axis=0, inplace=True)
    
    # drop Data Source Change column if it exists
    new_df.drop(list(new_df.filter(regex = 'Data Source Change')), axis = 1, inplace = True)

    # remove the first X characters from each item in the first row, to get just the year
    new_df.columns = [col[-4:] for col in new_df.columns]
    
    # insert the company name as a new row
    new_df.insert(1, "company", f.split('/')[1].split('.')[0])

    # rename the first column back to what it should be
    new_df.rename(columns={new_df.columns[0]: "For the Fiscal Period Ending" }, inplace=True)
    
    # remove any duplicated column names
    new_df = new_df.loc[:,~new_df.columns.duplicated()].copy()
    
    basic_eps_df_list.append(new_df)
    
    # display(HTML(new_df.to_html()))
    
basic_eps_df = pd.concat(basic_eps_df_list)

WARNING *** file size (837642) not 512 + multiple of sector size (512)
consumer_discretionary/NIKE_Inc_NYSE_NKE_Financials.xls
WARNING *** file size (788490) not 512 + multiple of sector size (512)
consumer_discretionary/LVMH_Moët_Hennessy_Louis_Vuitton_Société_Européenne_ENXTPA_MC_Financials.xls
WARNING *** file size (723466) not 512 + multiple of sector size (512)

/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/fraye/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

consumer_discretionary/Starbucks_Corporation_NasdaqGS_SBUX_Financials.xls
WARNING *** file size (804874) not 512 + multiple of sector size (512)
consumer_discretionary/The_Home_Depot_Inc_NYSE_HD_Financials.xls
WARNING *** file size (699914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Costco_Wholesale_Corporation_NasdaqGS_COST_Financials.xls
WARNING *** file size (811018) not 512 + multiple of sector size (512)
consumer_non_discretionary/Johnson_Johnson_NYSE_JNJ_Financials.xls
WARNING *** file size (827914) not 512 + multiple of sector size (512)
consumer_non_discretionary/Target_Corporation_NYSE_TGT_Financials.xls
WARNING *** file size (967178) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Coca_Cola_Company_NYSE_KO_Financials.xls
WARNING *** file size (866826) not 512 + multiple of sector size (512)
consumer_non_discretionary/The_Procter_Gamble_Company_NYSE_PG_Financials.xls
WARNING *** file size (879626) not 512 + multiple of sector size (512)
consumer_non_discretionary/Unilever_PLC_LSE_ULVR_Financials.xls
WARNING *** file size (802314) not 512 + multiple of sector size (512)
consumer_non_discretionary/Walmart_Inc_NYSE_WMT_Financials.xls
WARNING *** file size (857098) not 512 + multiple of sector size (512)
energy/BP_p_l_c_LSE_BP_Financials.xls
WARNING *** file size (871946) not 512 + multiple of sector size (512)
energy/Chevron_Corporation_NYSE_CVX_Financials.xls
WARNING *** file size (983562) not 512 + multiple of sector size (512)
energy/ConocoPhillips_NYSE_COP_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
energy/Exxon_Mobil_Corporation_NYSE_XOM_Financials.xls
WARNING *** file size (817162) not 512 + multiple of sector size (512)
energy/Shell_plc_LSE_SHEL_Financials.xls
WARNING *** file size (899594) not 512 + multiple of sector size (512)
financial_services/Bank_of_America_Corporation_NYSE_BAC_Financials.xls
WARNING *** file size (901130) not 512 + multiple of sector size (512)
financial_services/Citigroup_Inc_NYSE_C_Financials.xls
WARNING *** file size (914954) not 512 + multiple of sector size (512)
financial_services/JPMorgan_Chase_Co_NYSE_JPM_Financials_(1).xls
WARNING *** file size (648714) not 512 + multiple of sector size (512)
financial_services/Mastercard_Incorporated_NYSE_MA_Financials.xls
WARNING *** file size (755210) not 512 + multiple of sector size (512)
financial_services/Morgan_Stanley_NYSE_MS_Financials.xls
WARNING *** file size (718858) not 512 + multiple of sector size (512)
financial_services/The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials.xls
WARNING *** file size (571914) not 512 + multiple of sector size (512)
financial_services/Visa_Inc_NYSE_V_Financials.xls
WARNING *** file size (229898) not 512 + multiple of sector size (512)
healthcare/Centene_Corporation_NYSE_CNC_Financials.xls
WARNING *** file size (829450) not 512 + multiple of sector size (512)
healthcare/CVS_Health_Corporation_NYSE_CVS_Financials.xls
WARNING *** file size (741898) not 512 + multiple of sector size (512)
healthcare/Elevance_Health_Inc_NYSE_ELV_Financials.xls
WARNING *** file size (833546) not 512 + multiple of sector size (512)
healthcare/McKesson_Corporation_NYSE_MCK_Financials.xls
WARNING *** file size (921610) not 512 + multiple of sector size (512)
healthcare/The_Cigna_Group_NYSE_CI_Financials.xls
WARNING *** file size (703498) not 512 + multiple of sector size (512)
healthcare/UnitedHealth_Group_Incorporated_NYSE_UNH_Financials.xls
WARNING *** file size (521738) not 512 + multiple of sector size (512)
technology/Alphabet_Inc_NasdaqGS_GOOGL_Financials.xls
WARNING *** file size (638474) not 512 + multiple of sector size (512)
technology/Amazon_com_Inc_NasdaqGS_AMZN_Financials.xls
WARNING *** file size (689162) not 512 + multiple of sector size (512)
technology/Apple_Inc_NasdaqGS_AAPL_Financials.xls
WARNING *** file size (350218) not 512 + multiple of sector size (512)
technology/Meta_Platforms_Inc_NasdaqGS_META_Financials.xls
WARNING *** file size (680970) not 512 + multiple of sector size (512)
technology/Microsoft_Corporation_NasdaqGS_MSFT_Financials.xls
WARNING *** file size (425994) not 512 + multiple of sector size (512)
technology/Tesla_Inc_NasdaqGS_TSLA_Financials_(1).xls

In [256]:
basic_eps_df

,For the Fiscal Period Ending,company,1984,1985,1986,1987,1988,1989,1990,1991,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,ange
64,Basic EPS,NIKE_Inc_NYSE_NKE_Financials,0.02,0,0.02,0.01,0.04,0.07,0.1,0.12,...,1.9,2.21,2.56,1.19,2.55,1.63,3.64,3.83,3.51,NaN
67,Basic EPS,LVMH_Moët_Hennessy_Louis_Vuitton_Société_Eu...,NaN,NaN,NaN,NaN,NaN,1.19,1.5,1.63,...,7.72,8.36,12.26,14.47,15.99,11.42,27.18,29.98,NaN,NaN
67,Basic EPS,Starbucks_Corporation_NasdaqGS_SBUX_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,1.84,1.91,1.99,3.27,2.95,0.79,3.57,2.85,2.89,NaN
67,Basic EPS,The_Home_Depot_Inc_NYSE_HD_Financials,NaN,0.01,0.01,0.02,0.04,0.05,0.07,0.1,...,4.74,5.49,6.47,7.33,9.78,10.29,11.98,15.59,16.74,NaN
66,Basic EPS,Costco_Wholesale_Corporation_NasdaqGS_COST_Fin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,...,5.41,5.36,6.11,7.15,8.32,9.05,11.3,13.17,13.63,NaN
67,Basic EPS,Johnson_Johnson_NYSE_JNJ_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.55,...,NaN,5.56,6.04,5.7,5.72,NaN,5.59,7.93,6.83,NaN
67,Basic EPS,Target_Corporation_NYSE_TGT_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.58,5.36,4.74,5.37,5.56,6.42,8.73,14.23,6.02,NaN
69,Basic EPS,The_Coca_Cola_Company_NYSE_KO_Financials,NaN,NaN,0.15,0.15,0.18,0.31,0.25,0.3,...,1.69,1.51,0.29,1.51,2.09,1.8,2.26,2.2,NaN,NaN
64,Basic EPS,The_Procter_Gamble_Company_NYSE_PG_Financials,NaN,NaN,NaN,NaN,NaN,0.44,0.56,0.61,...,2.5,3.8,5.8,3.75,1.45,5.13,5.69,6,NaN,NaN
67,Basic EPS,Unilever_PLC_LSE_ULVR_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.88,1.93,2.59,4.01,2.41,2.61,2.65,3.21,NaN,NaN
64,Basic EPS,Walmart_Inc_NYSE_WMT_Financials,NaN,NaN,0.07,0.1,0.14,0.19,0.24,0.29,...,5.07,4.58,4.4,3.29,2.28,5.22,4.77,4.9,4.29,NaN
68,Basic EPS,BP_p_l_c_LSE_BP_Financials,NaN,NaN,NaN,NaN,NaN,0.26,0.3,0.07,...,-0.35,0.01,0.17,0.47,0.2,-1,0.38,-0.13,NaN,NaN
68,Basic EPS,Chevron_Corporation_NYSE_CVX_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.92,...,2.46,-0.27,4.88,7.81,1.55,-2.96,8.16,18.37,NaN,NaN
71,Basic EPS,ConocoPhillips_NYSE_COP_Financials,NaN,NaN,NaN,NaN,1.36,0.45,1.56,0.5,...,-3.57,-2.9,-0.7,5.36,6.43,-2.51,6.1,14.62,NaN,NaN
68,Basic EPS,Exxon_Mobil_Corporation_NYSE_XOM_Financials,NaN,NaN,NaN,NaN,NaN,NaN,0.99,1.11,...,3.85,1.88,4.63,4.88,3.36,-5.25,5.39,13.26,NaN,NaN
66,Basic EPS,Shell_plc_LSE_SHEL_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.31,0.58,1.58,2.82,1.97,-2.78,2.59,5.76,NaN,NaN
77,Basic EPS,Bank_of_America_Corporation_NYSE_BAC_Financials,NaN,NaN,NaN,NaN,NaN,1.12,0.65,0.19,...,1.38,1.58,1.63,2.64,2.77,1.88,3.6,3.21,NaN,NaN
72,Basic EPS,Citigroup_Inc_NYSE_C_Financials,NaN,NaN,NaN,NaN,NaN,NaN,1.34,1.76,...,5.41,4.72,-2.98,6.69,8.08,4.74,10.21,7.04,NaN,NaN
76,Basic EPS,JPMorgan_Chase_Co_NYSE_JPM_Financials_(1),NaN,NaN,NaN,NaN,NaN,NaN,1.78,1.97,...,6.06,6.24,6.35,9.04,10.75,8.89,15.39,12.1,NaN,NaN
65,Basic EPS,Mastercard_Incorporated_NYSE_MA_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.36,3.7,3.67,5.63,7.98,6.4,8.79,10.26,NaN,NaN
69,Basic EPS,Morgan_Stanley_NYSE_MS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.97,2.98,3.14,4.81,5.26,6.55,8.16,6.23,NaN,FYC
65,Basic EPS,The_Goldman_Sachs_Group_Inc_NYSE_GS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.35,16.53,9.12,25.53,21.18,24.94,60.25,30.42,NaN,FYC
65,Basic EPS,Visa_Inc_NYSE_V_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.58,2.49,2.81,4.44,5.33,4.9,5.64,7.02,NaN,NaN
62,Basic EPS,Centene_Corporation_NYSE_CNC_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.4,2.31,3.19,3.17,2.31,2.09,NaN,NaN
65,Basic EPS,CVS_Health_Corporation_NYSE_CVS_Financials,NaN,NaN,NaN,NaN,NaN,NaN,0.94,0.8,...,4.66,4.93,6.47,-0.57,5.1,5.48,6,3.16,NaN,NaN
61,Basic EPS,Elevance_Health_Inc_NYSE_ELV_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.73,9.39,14.7,14.53,18.81,18.23,25.04,25.1,NaN,NaN
67,Basic EPS,McKesson_Corporation_NYSE_MCK_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.36,9.82,22.94,0.32,0.17,4.97,-28.26,7.31,NaN,NaN
65,Basic EPS,The_Cigna_Group_NYSE_CI_Financials,NaN,NaN,NaN,NaN,0.59,0.78,0.48,0.7,...,8.17,7.31,8.92,10.69,13.58,23.17,15.87,21.54,NaN,NaN
63,Basic EPS,UnitedHealth_Group_Incorporated_NYSE_UNH_Finan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.1,7.37,10.95,12.45,14.55,16.23,18.33,21.47,NaN,NaN
68,Basic EPS,Alphabet_Inc_NasdaqGS_GOOGL_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.19,1.42,0.91,2.21,2.48,2.96,5.69,4.59,NaN,NaN
67,Basic EPS,Amazon_com_Inc_NasdaqGS_AMZN_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.06,0.25,0.32,1.03,1.17,2.13,3.3,-0.27,NaN,NaN
64,Basic EPS,Apple_Inc_NasdaqGS_AAPL_Financials,NaN,NaN,NaN,NaN,0.03,0.03,0.03,0.02,...,2.32,2.09,2.32,3,2.99,3.31,5.67,6.15,NaN,NaN
63,Basic EPS,Meta_Platforms_Inc_NasdaqGS_META_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.31,3.56,5.49,7.65,6.48,10.22,13.99,8.63,NaN,NaN
68,Basic EPS,Microsoft_Corporation_NasdaqGS_MSFT_Financials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,...,1.49,2.12,2.74,2.15,5.11,5.82,8.12,9.7,NaN,NaN
66,Basic EPS,Tesla_Inc_NasdaqGS_TSLA_Financials_(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.46,-0.31,-0.79,-0.38,-0.32,0.25,1.87,4.02,NaN,NaN

In [262]:
conda install openpyxl

Collecting package metadata (current_repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-64::pillow==9.0.1=py38hde71d04_0
  - defaults/osx-64::lcms2==2.12=hf1fd2bf_0
  - defaults/osx-64::libwebp==1.2.0=hacca55c_0
  - defaults/osx-64::anaconda-navigator==2.1.0=py38hecd8cb5_0
  - defaults/osx-64::openjpeg==2.4.0=h66ea3da_0
  - defaults/osx-64::libtiff==4.2.0=h87d7836_0
done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/fraye/opt/anaconda3

  added / updated specs:
    - openpyxl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    et_xmlfile-1.1.0           |   py38hecd8cb5_0          10 KB
    openpyxl-3.0.10            |   py38hca72f7f_0         510 KB
    ------------------------------------------------------------
                                           Total:         520 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         pkgs/main/osx-64::et_xmlfile-1.1.0-py38hecd8cb5_0 None
  openpyxl           pkgs/main/osx-64::openpyxl-3.0.10-py38hca72f7f_0 None

The following packages will be DOWNGRADED:

  zstd                                     1.4.9-h322a384_0 --> 1.4.5-h41d2c2f_0 None



Downloading and Extracting Packages
et_xmlfile-1.1.0     | 10 KB     | ##################################### | 100%
openpyxl-3.0.10      | 510 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [263]:
# convert to xls

# Write each dataframe to a different worksheet.
with pd.ExcelWriter('company_data_EMDS.xlsx') as writer:  
    revenue_df.to_excel(writer, sheet_name='Revenue')
    operating_income_df.to_excel(writer, sheet_name='Operating Income')
    rd_exp_df.to_excel(writer, sheet_name='R&D Expense')
    gross_margin_percentage_df.to_excel(writer, sheet_name='Gross Profit Margin (%)')
    cash_from_investing_df.to_excel(writer, sheet_name='Cash From Investing')
    basic_eps_df.to_excel(writer, sheet_name='Basic EPS')